# Generated by Django 5.2.11 on 2026-03-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
