# Generated by Django 5.2.11 on 2026-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='violation_count',
            field=models.IntegerField(default=0),
        ),
    ]
