# Generated by Django 5.2.11 on 2026-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_blockedip_violation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='last_violation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
