# Generated by Django 5.2.11 on 2026-06-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_blockedip_last_violation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, unique=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
